const Account = require('./account');
const Verification = require('./verification');
const Settings = require('./settings');
const Organization = require('./organization');
const OrgSettings = require('./org_set');
const Category = require('./categories');
const Employee = require('./employee');
const File = require('./file');
const Favourite = require('./favr_files');
const EmployeeDT = require('./employeeDT');
const Project = require('./projects');
const Assigned = require('./assigned');
const UserFiles = require('./user_file');
const UserCategory = require('./user_category');
const ShareFile = require('./sharedFile');
const SharedCat = require('./sharedCat');
const SharedNote = require('./share_note');
const Note = require('./notes');
const Recording = require('./recording');
const ClientCategory = require('./clientCategory');
const ClientFiles = require('./clientFiles');
const Notification = require('./notifications');
const ProjectCat = require('./projectCategory');
const ProjectFiles = require('./project_files');
const Discussion = require('./discussion');
const Task = require('./tasks');
const SharedTask = require('./share_task');
const Plans = require('./plans');
const Service = require('./service');
const Registeration = require('./registration');
const DailyPlan = require('./daily_plan');
const EasyPaisa = require('./easy_paisa');
const Billing = require('./billing');
const ShareFileC = require('./clientApp/sharedFile');
const ClientFileC = require('./clientApp/clientFiles');
const Announcement = require('./announcement');
const SetsC = require('./clientApp/settings');
const Poll = require('./polls');
const RegisterationP = require('./personal/routes/registration');
const AccountP = require('./personal/routes/account');
const DailyPlanP = require('./personal/routes/daily_plan');
const PlanP = require('./personal/routes/plans');
const UserFilesP = require('./personal/routes/user_file');
const UserCategoryP = require('./personal/routes/user_category');
const ShareFileP = require('./personal/routes/sharedFile');
const ClientCategoryC = require('./personal/routes/clientCategory');
const ClientFilesC = require('./personal/routes/clientFiles');
const NotifC = require('./personal/routes/notifications');
const FileC = require('./personal/routes/file');
const FavouriteC = require('./personal/routes/favr_files');
const BillingC = require('./personal/routes/billing');

module.exports = function (app) {
    app.use('/api/account', Account);
    app.use('/api/verification', Verification);
    app.use('/api/settings', Settings);
    app.use('/api/organization', Organization);
    app.use('/api/org_settings', OrgSettings);
    app.use('/api/category', Category);
    app.use('/api/employee', Employee);
    app.use('/api/file', File);
    app.use('/api/favourite', Favourite);
    app.use('/api/employeeDT', EmployeeDT);
    app.use('/api/project', Project);
    app.use('/api/assigned', Assigned);
    app.use('/api/user_file', UserFiles);
    app.use('/api/user_category', UserCategory);
    app.use('/api/share', ShareFile);
    app.use('/api/share_cat', SharedCat);
    app.use('/api/note', Note);
    app.use('/api/share_note', SharedNote);
    app.use('/api/recording', Recording);
    app.use('/api/client_category', ClientCategory);
    app.use('/api/client_file', ClientFiles);
    app.use('/api/notifications', Notification);
    app.use('/api/project_category', ProjectCat);
    app.use('/api/project_file', ProjectFiles);
    app.use('/api/discussion', Discussion);
    app.use('/api/task', Task);
    app.use('/api/share_task', SharedTask);
    app.use('/api/plan', Plans);
    app.use('/api/poll', Poll);
    app.use('/api/service', Service);
    app.use('/api/registration', Registeration);
    app.use('/api/daily', DailyPlan);
    app.use('/api/easy_paisa', EasyPaisa);
    app.use('/api/billing', Billing);
    app.use('/apiC/shared', ShareFileC);
    app.use('/apiC/client', ClientFileC);
    app.use('/apiC/settings', SetsC);
    app.use('/api/announcements', Announcement);
    app.use('/apiP/registration', RegisterationP);
    app.use('/apiP/account', AccountP);
    app.use('/apiP/daily', DailyPlanP);
    app.use('/apiP/plan', PlanP);
    app.use('/apiP/user_file', UserFilesP);
    app.use('/apiP/user_category', UserCategoryP);
    app.use('/apiP/share', ShareFileP);
    app.use('/apiP/client_category', ClientCategoryC);
    app.use('/apiP/client_file', ClientFilesC);
    app.use('/apiP/notifications', NotifC);
    app.use('/apiP/file', FileC);
    app.use('/apiP/favourite', FavouriteC);
    app.use('/apiP/billing', BillingC);
};