const Account = require('./account');
const Verification = require('./verification');
const Settings = require('./settings');
const Organization = require('./organization');
const OrgSettings = require('./org_set');
const Category = require('./categories');
const Roles = require('./roles');
const Employee = require('./employee');
const File = require('./file');
const Favourite = require('./favr_files');
const EmployeeDT = require('./employeeDT');
const Project = require('./projects');
const Assigned = require('./assigned');
const UserFiles = require('./user_file');
const UserCategory = require('./user_category');
const ShareFile = require('./sharedFile');
const SharedCat = require('./sharedCat');
const SharedNote = require('./share_note');
const Note = require('./notes');
const Recording = require('./recording');
const ClientCategory = require('./clientCategory');
const ClientFiles = require('./clientFiles');
const Notification = require('./notifications');
const ProjectCat = require('./projectCategory');
const ProjectRole = require('./projectRoles');
const ProjectFiles = require('./project_files');
const Ticket = require('./ticket');
const Discussion = require('./discussion');
const Task = require('./tasks');
const SharedTask = require('./share_task');
const Plans = require('./plans');

module.exports = function (app) {
    app.use('/api/account', Account);
    app.use('/api/verification', Verification);
    app.use('/api/settings', Settings);
    app.use('/api/organization', Organization);
    app.use('/api/org_settings', OrgSettings);
    app.use('/api/category', Category);
    app.use('/api/roles', Roles);
    app.use('/api/employee', Employee);
    app.use('/api/file', File);
    app.use('/api/favourite', Favourite);
    app.use('/api/employeeDT', EmployeeDT);
    app.use('/api/project', Project);
    app.use('/api/assigned', Assigned);
    app.use('/api/user_file', UserFiles);
    app.use('/api/user_category', UserCategory);
    app.use('/api/share', ShareFile);
    app.use('/api/share_cat', SharedCat);
    app.use('/api/note', Note);
    app.use('/api/share_note', SharedNote);
    app.use('/api/recording', Recording);
    app.use('/api/client_category', ClientCategory);
    app.use('/api/client_file', ClientFiles);
    app.use('/api/notifications', Notification);
    app.use('/api/project_category', ProjectCat);
    app.use('/api/project_roles', ProjectRole);
    app.use('/api/project_file', ProjectFiles);
    app.use('/api/ticket', Ticket);
    app.use('/api/discussion', Discussion);
    app.use('/api/task', Task);
    app.use('/api/share_task', SharedTask);
    app.use('/api/plan', Plans);
}